# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oppo/sm8250-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter OP4A7A,$(TARGET_DEVICE)),)

endif
